results_dir: /results/stylegan_xl_16_to32_to64

encryption_key: tlt_encode
task: stylegan
train:
  resume_training_checkpoint_path: null
  pretrained_model_path: null
  num_epochs: 3000
  num_nodes: 1
  num_gpus: 8
  gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
  deterministic_all: False
  validation_interval: 10
  checkpoint_interval: 1
  stylegan:
    gan_seed_offset: 0  # Try when encountering GAN mode collapsed
    optim_generator:
      lr: 0.0025
      optim: "Adam"
      betas: [0, 0.99]
      eps: 1e-08
    optim_discriminator:
      lr: 0.002
      optim: "Adam"
      betas: [0, 0.99]
      eps: 1e-08
  results_dir: "${results_dir}/train"
  tensorboard:
    enabled: True
    infrequent_logging_frequency: 1

model:
  input_embeddings_path: /data/tf_efficientnet_lite0_embed.pth
  generator:
    backbone: stylegan3-t
    superres: True
    added_head_superres: ## Ignore when the superres == False
      head_layers: [4, 4]
      up_factor: [2, 2]
      pretrained_stem_path: /results/stylegan_xl_16_to32/train/styleganxl_model_latest.pth
      reinit_stem_anyway: False
    stem: 
      fp32: False
      cbase: 16384
      cmax: 256
      syn_layers: 7
      resolution: 16

  stylegan:
    loss:
      cls_weight: 0.0
    discriminator:
      backbones: ["deit_base_distilled_patch16_224", "tf_efficientnet_lite0"]
    metrics:
      inception_fid_path: /data/InceptionV3.pth


dataset:
  common:
    cond: True
    num_classes: 6 # be 0 when cond==True
    img_channels: 3
    img_resolution: 64
  stylegan:
    train_dataset:
      images_dir: /results/dataset_convert/train_64.zip
    validation_dataset:
      images_dir: /results/dataset_convert/train_64.zip
    test_dataset:
      images_dir: /results/dataset_convert/train_64.zip
    infer_dataset:
      start_seed: 0
      end_seed: 50
    mirror: True

  batch_size: 16
  workers: 3


evaluate: 
  num_nodes: 1
  num_gpus: 8
  gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
  checkpoint: /results/stylegan_xl_16_to32_to64/train/styleganxl_model_latest.pth
inference:
  num_nodes: 1
  num_gpus: 8
  gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
  checkpoint: /results/stylegan_xl_16_to32_to64/train/styleganxl_model_latest.pth
  class_idx: 0
  truncation_psi: 0.0
  translate: [0.0, 0.0]
  rotate: 0.0