evaluate:
  num_gpus: 1
dataset:
  test_data_sources:
    image_dir: /data/HardHatWorkers/raw/valid/
    json_file: /data/odvg/annotations/annotations_without_background_remapped.json
  batch_size: 8
  workers: 8
model:
  backbone: swin_tiny_224_1k
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 900
  dropout_ratio: 0.0
  dim_feedforward: 2048
  log_scale: auto
  class_embed_bias: True
