results_dir: /results/of_3d_ptm
encryption_key: nvidia_tao
model:
  model_type: of
  backbone: resnet_18
  of_seq_length: 3
  input_type: 3d
  input_height: 224
  input_width: 224
  sample_strategy: consecutive
  dropout_ratio: 0.0
dataset:
  train_dataset_dir: /data/train
  val_dataset_dir: /data/test
  label_map:
    fall_floor: 0
    ride_bike: 1
  batch_size: 32
  workers: 8
  clips_per_video: 5
  augmentation_config:
    train_crop_type: no_crop
    horizontal_flip_prob: 0.5
    of_input_mean: [0.5]
    of_input_std: [0.5]
    val_center_crop: False
train:
  optim:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001
    lr_scheduler: MultiStep
    lr_steps: [5, 15, 20]
    lr_decay: 0.1
  num_epochs: 20
  checkpoint_interval: 1
  num_gpus: 1
evaluate:
  checkpoint: "??"
  test_dataset_dir: "??"
inference:
  checkpoint: "??"
  inference_dataset_dir: "??"
export:
  checkpoint: "??"
