inference:
  conf_threshold: 0.5
  input_width: 960
  input_height: 544
  color_map:
    person: green
    car: red
    cat: blue
dataset:
  infer_data_sources:
    image_dir: 
     - /data/raw-data/val2017/
    classmap: /data/raw-data/annotations/classmap.txt
  num_classes: 91
  batch_size: 8
  workers: 8
  augmentation:
    fixed_padding: False
model:
  backbone: fan_small
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 900
  num_select: 100
  dropout_ratio: 0.0
  dim_feedforward: 2048