inference:
  conf_threshold: 0.5
  color_map:
    person: green
    car: red
    cat: blue
dataset:
  infer_data_sources:
    image_dir: 
     - /data/raw-data/val2017/
    captions: ["person", "car", "cat"]
    data_type: OD
  batch_size: 1
  workers: 1
model:
  backbone: swin_tiny_224_1k
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 900
  dropout_ratio: 0.0
  dim_feedforward: 2048
  loss_types: ['labels', 'boxes', 'masks', 'rela']
  log_scale: auto
  class_embed_bias: True
  num_region_queries: 100
