train:
  exp_config:
    manual_seed: 49
  train_config:
    runner:
      max_epochs: 40
    checkpoint_config:
      interval: 1
    logging:
      interval: 500
    validate: True
    evaluation:
      interval: 1
    custom_hooks:
      - type: "EMAHook"
        momentum: 4e-5
        priority: "ABOVE_NORMAL"
dataset:
  data:
    samples_per_gpu: 8
    train:
      data_prefix: /data/cats_dogs_dataset/training_set/training_set/
      pipeline: # Augmentations alone
        - type: RandomResizedCrop
          size: 224
        - type: RandomFlip
          flip_prob: 0.5
          direction: "horizontal"
      classes: /data/cats_dogs_dataset/classes.txt
    val:
      data_prefix: /data/cats_dogs_dataset/val_set/val_set
      classes: /data/cats_dogs_dataset/classes.txt
    test:
      data_prefix: /data/cats_dogs_dataset/val_set/val_set
      classes: /data/cats_dogs_dataset/classes.txt
model:
  backbone:
    type: "fan_small_12_p4_hybrid"
    custom_args:
      drop_path: 0.1
  head:
    type: "FANLinearClsHead"
    custom_args:
      head_init_scale: 1
    num_classes: 2
    loss:
      type: "CrossEntropyLoss"
      loss_weight: 1.0
      use_soft: False
